daemon off;
master_process off;
error_log logs/error.log debug;

events {
    worker_connections 512;
}

httplite {
    server {
        listen 8888;
        server_name 192.168.1.1;
    }

    upstreams {
        keep_alive 10000;
        server 127.0.0.1:8889 connections=2;
        # server 127.0.0.1:8890 connections=2;
        # server 127.0.0.1:8891 connections=2;
    }
}
