#!/bin/bash

if [ -s /root/.config/gdb/gdbinit ]
then
  exit
fi

mkdir /root/.config
mkdir /root/.config/gdb

echo "add-auto-load-safe-path /workspaces/nginx-layer-6/.gdbinit" > /root/.config/gdb/gdbinit
